import os
import hmac
import hashlib
import requests
from flask import Flask, request, jsonify

app = Flask(__name__)

# ── Config (set these as environment variables) ──────────────────────────────
GITLAB_TOKEN   = os.environ.get("GITLAB_TOKEN")        # Personal Access Token, scope: api
WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET", "")  # Secret token you set in GitLab
ANTHROPIC_KEY  = os.environ.get("ANTHROPIC_API_KEY")
GITLAB_URL     = os.environ.get("GITLAB_URL", "https://gitlab.com")

SYSTEM_PROMPT = """You are an External Prefrontal Cortex for software developers with ADHD.
Your sole purpose is Task Atomicization: transforming a vague GitLab Issue into a
psychologically safe, executable action plan.

RULES:
1. Every sub-task ≤ 15 minutes, completable alone right now.
2. Each task starts with ONE concrete verb: Open, Read, Write, Run, Add, Check, Delete, Search.
   FORBIDDEN: Implement, Handle, Manage, Fix, Deal with.
3. Every task ends with: ✓ Done when: [specific observable outcome]
4. If labels contain Critical/P0/Blocker/Security — one calm sentence acknowledging it, then decompose normally.
5. Maximum 8 tasks. If more needed, split into "Start here →" and "After your break →".
6. Blockers (needs another person) go in a separate section.

OUTPUT FORMAT — return ONLY this, no preamble:

---
**[Reframed action-oriented title — max 10 words]**

> [One calm sentence: the core of this task, no threat language.]

**Start here →**
- [ ] Verb specific-object — ✓ Done when: observable outcome
- [ ] Verb specific-object — ✓ Done when: observable outcome

**Then →**
- [ ] Verb specific-object — ✓ Done when: observable outcome

🔒 **Blockers (waiting on others):**
- [omit section entirely if none]
---

Tone: direct, warm, precise. Like a trusted senior colleague leaving a quiet note."""


def verify_signature(payload: bytes, signature: str) -> bool:
    if not WEBHOOK_SECRET:
        return True
    expected = hmac.new(
        WEBHOOK_SECRET.encode(), payload, hashlib.sha256
    ).hexdigest()
    return hmac.compare_digest(f"sha256={expected}", signature or "")


def call_claude(issue_text: str) -> str:
    resp = requests.post(
        "https://api.anthropic.com/v1/messages",
        headers={
            "x-api-key": ANTHROPIC_KEY,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        json={
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 1000,
            "system": SYSTEM_PROMPT,
            "messages": [{"role": "user", "content": f"GitLab Issue:\n\n{issue_text}"}],
        },
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()["content"][0]["text"]


def post_note(project_id: int | str, issue_iid: int, body: str):
    url = f"{GITLAB_URL}/api/v4/projects/{project_id}/issues/{issue_iid}/notes"
    resp = requests.post(
        url,
        headers={"PRIVATE-TOKEN": GITLAB_TOKEN},
        json={"body": body},
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()


@app.route("/webhook", methods=["POST"])
def webhook():
    # ── 1. Verify signature ───────────────────────────────────────────────
    raw = request.get_data()
    sig = request.headers.get("X-Gitlab-Token", "")
    # GitLab sends the secret token directly (not HMAC), so compare plaintext
    if WEBHOOK_SECRET and sig != WEBHOOK_SECRET:
        return jsonify({"error": "unauthorized"}), 401

    payload = request.get_json(force=True, silent=True) or {}

    # ── 2. Filter: only act on issue assignment events ────────────────────
    event = request.headers.get("X-Gitlab-Event", "")
    if event not in ("Issue Hook", "Work Item Hook"):
        return jsonify({"status": "ignored", "event": event}), 200

    action   = payload.get("object_attributes", {}).get("action", "")
    assignees = payload.get("assignees", [])

    # Trigger on: issue opened OR just assigned
    if action not in ("open", "update") or not assignees:
        return jsonify({"status": "ignored", "action": action}), 200

    # ── 3. Extract issue content ──────────────────────────────────────────
    attrs       = payload["object_attributes"]
    title       = attrs.get("title", "")
    description = attrs.get("description", "") or ""
    labels      = " ".join(l.get("title", "") for l in payload.get("labels", []))
    issue_iid   = attrs["iid"]
    project_id  = payload["project"]["id"]

    issue_text = f"Title: {title}\nLabels: {labels}\n\nDescription:\n{description}"

    # ── 4. Atomicize via Claude ───────────────────────────────────────────
    try:
        atomicized = call_claude(issue_text)
    except Exception as e:
        return jsonify({"error": f"Claude API failed: {e}"}), 500

    # ── 5. Post back to GitLab as a note ─────────────────────────────────
    note_body = (
        "### 🧠 Cognitive Orthotic — Task Breakdown\n\n"
        + atomicized
        + "\n\n---\n*Generated by Cognitive Orthotic Agent · "
          "[What is this?](https://github.com/yourrepo)*"
    )

    try:
        post_note(project_id, issue_iid, note_body)
    except Exception as e:
        return jsonify({"error": f"GitLab note failed: {e}"}), 500

    return jsonify({"status": "ok", "issue": issue_iid}), 200


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "alive"}), 200


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
