import os
import hmac
import hashlib
import requests
from flask import Flask, request, jsonify

app = Flask(__name__)

GITHUB_TOKEN   = os.environ.get("GITHUB_TOKEN")
WEBHOOK_SECRET = os.environ.get("WEBHOOK_SECRET", "")
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

SYSTEM_PROMPT = """You are an External Prefrontal Cortex for software developers with ADHD.
Your sole purpose is Task Atomicization: transforming a vague GitHub Issue into a
psychologically safe, executable action plan.

RULES:
1. Every sub-task must be completable in 15 minutes or less, alone, right now.
2. Each task starts with ONE concrete verb: Open, Read, Write, Run, Add, Check, Delete, Search.
   FORBIDDEN verbs: Implement, Handle, Manage, Fix, Deal with.
3. Every task ends with: ✓ Done when: [specific observable outcome]
4. If labels contain Critical/P0/Blocker/Security — one calm sentence acknowledging it, then decompose normally.
5. Maximum 8 tasks total. If more needed, split into "Start here →" and "After your break →".
6. Anything requiring another person goes in the Blockers section.

OUTPUT FORMAT — return ONLY this structure, no preamble:

---
**[Reframed action-oriented title — max 10 words]**

> [One calm sentence: the core of this task, no threat language.]

**Start here →**
- [ ] Verb specific-object — ✓ Done when: observable outcome
- [ ] Verb specific-object — ✓ Done when: observable outcome

**Then →**
- [ ] Verb specific-object — ✓ Done when: observable outcome

🔒 **Blockers (waiting on others):**
- [omit this section entirely if none]
---

Tone: direct, warm, precise. Like a trusted senior colleague leaving a quiet note."""


def verify_signature(payload: bytes, signature: str) -> bool:
    if not WEBHOOK_SECRET:
        return True
    mac = hmac.new(WEBHOOK_SECRET.encode(), payload, hashlib.sha256).hexdigest()
    return hmac.compare_digest(f"sha256={mac}", signature or "")


def call_gemini(issue_text: str) -> str:
    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"gemini-1.5-flash:generateContent?key={GEMINI_API_KEY}"
    )
    body = {
        "system_instruction": {"parts": [{"text": SYSTEM_PROMPT}]},
        "contents": [{"parts": [{"text": f"GitHub Issue:\n\n{issue_text}"}]}],
        "generationConfig": {"maxOutputTokens": 1000, "temperature": 0.3},
    }
    resp = requests.post(url, json=body, timeout=30)
    resp.raise_for_status()
    return resp.json()["candidates"][0]["content"]["parts"][0]["text"]


def post_github_comment(owner: str, repo: str, issue_number: int, body: str):
    url = f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_number}/comments"
    resp = requests.post(
        url,
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
        },
        json={"body": body},
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()


@app.route("/webhook", methods=["POST"])
def webhook():
    # 1. Verify signature
    raw = request.get_data()
    sig = request.headers.get("X-Hub-Signature-256", "")
    if WEBHOOK_SECRET and not verify_signature(raw, sig):
        return jsonify({"error": "unauthorized"}), 401

    payload = request.get_json(force=True, silent=True) or {}

    # 2. Only handle issue assignment
    action = payload.get("action", "")
    if action != "assigned":
        return jsonify({"status": "ignored", "action": action}), 200

    # 3. Extract issue content
    issue      = payload.get("issue", {})
    title      = issue.get("title", "")
    body       = issue.get("body", "") or ""
    labels     = " ".join(l.get("name", "") for l in issue.get("labels", []))
    number     = issue.get("number")
    repo_info  = payload.get("repository", {})
    owner      = repo_info.get("owner", {}).get("login", "")
    repo_name  = repo_info.get("name", "")

    issue_text = f"Title: {title}\nLabels: {labels}\n\nDescription:\n{body}"

    # 4. Atomicize via Gemini
    try:
        atomicized = call_gemini(issue_text)
    except Exception as e:
        return jsonify({"error": f"Gemini API failed: {e}"}), 500

    # 5. Post back as GitHub comment
    note_body = (
        "### 🧠 Cognitive Orthotic — Task Breakdown\n\n"
        + atomicized
        + "\n\n---\n*Generated by [Cognitive Orthotic](https://github.com/"
        + owner + "/cognitive-orthotic) · External prefrontal cortex for ADHD developers*"
    )

    try:
        post_github_comment(owner, repo_name, number, note_body)
    except Exception as e:
        return jsonify({"error": f"GitHub comment failed: {e}"}), 500

    return jsonify({"status": "ok", "issue": number}), 200


@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "alive"}), 200


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=False)
